name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
          date
          ls -l

  a_test_job:
    runs-on: ubuntu-20.04
    if:  ${{(contains(join(github.event.commits.*.message,' ,' ), '#skip') != 'true')  }}  
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          CONTAINS: ${{contains(join( github.event.commits.*.message,' ,' ), '#skip') != 'true'}}
        run: echo "$COMMIT_MESSAGES $CONTAINS"

  